version: '3.4'
x-logging:
  &default-logging
  # options:
  #   loki-url: http://host.docker.internal:7004/loki/api/v1/push
  driver: json-file

services:
  spry.identity:
    image: ${DOCKER_REGISTRY-}spryidentity
    build:
      context: ../Spry.Identity
      dockerfile: Spry.Identity/Dockerfile
    environment:
     - IdentityServer__Issuer=http://host.docker.internal:5312
     - DisableRedirectUriValidation=true
     - DisablePostLogoutRedirectUriValidation=true
     - EventBus__Connection=rabbitmq
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__SprySSOIdentity=Server=postgres.data;Port=5432;User Id=postgres;Password=spry-password;Database=spry_sso_identity;Pooling=true;MaxPoolSize=50;
     - ConnectionStrings__SpryRedisStore=redis.data,abortConnect=false
    networks: 
      spryid:
    ports:
     - "5312:8080"
  #   depends_on: 
  #     - postgres.data
  #     - rabbitmq
  #     - redis.data

  # redis.data:
  #   image: redis:5-alpine
  #   logging: *default-logging
  #   networks: 
  #     spryid:
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redisdata:/data

  # postgres.data:
  #   image: postgres:11
  #   logging: *default-logging
  #   networks: 
  #     spryid:
  #   environment:
  #     - POSTGRES_PASSWORD=spry-password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data 
  
  # rabbitmq:
  #   image: rabbitmq:3.8-management-alpine
  #   logging: *default-logging
  #   networks: 
  #     spryid:
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=spry-password
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   volumes:
  #    - rabbitdata:/var/lib/rabbitmq

  # pgadmin:
  #   image: dpage/pgadmin4 #dpage/pgadmin4
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: info@spryonline.com
  #     PGADMIN_DEFAULT_PASSWORD: spry-password
  #   networks:
  #     spryid:
  #   volumes:
  #     - pgadmindata:/var/lib/pgadmin
  #   ports: 
  #     - "5103:80"
  #   depends_on:
  #     - postgres.data

networks: 
  spryid:

volumes:
  pgdata:
  pgadmindata:
  rabbitdata:
  redisdata:
  